CREATE TABLE TABLENAME
(
ID INT NOT NULL UNIQUE PRIMARY KEY, -- THESE ARE CALLED FIELDS WITH CONSTRAINTS
NAME VARCHAR(50), -- SPECIFY THE SIZE OF THE STRING, IF NOT YOU WILL BE RESTRICTED TO 0 CHARACTERS
SALARY DECIMAL(18,10), -- SAVE UP TO 10 DECIMAL PLACES

)